using System;

namespace Hibernate.Domain
{
    public class Patient
    {
        public virtual int Id { get; set; }
        public virtual string Name { get; set; }
        public virtual int Age { get; set; }
        public virtual int Age1 { get; set; }
        public virtual int Age2 { get; set; }
        public virtual int Age3 { get; set; }
        public virtual int Age4 { get; set; }
        public virtual int Age5 { get; set; }
        public virtual int Age6 { get; set; }
        public virtual int Age7 { get; set; }
        public virtual int Age8 { get; set; }
        public virtual int Age9 { get; set; }
        public virtual int Age10 { get; set; }
        public virtual int Age11 { get; set; }
        public virtual int Age12 { get; set; }
        public virtual int Age13 { get; set; }
        public virtual int Age14 { get; set; }
        public virtual int Age15 { get; set; }
        public virtual int Age16 { get; set; }
        public virtual int Age17 { get; set; }
        public virtual int Age18 { get; set; }
        public virtual int Age19 { get; set; }
        public virtual int Age20 { get; set; }
        public virtual int Age21 { get; set; }
        public virtual int Age22 { get; set; }
        public virtual int Age23 { get; set; }
        public virtual int Age24 { get; set; }
        public virtual int Age25 { get; set; }
        public virtual int Age26 { get; set; }
        public virtual int Age27 { get; set; }
        public virtual int Age28 { get; set; }
        public virtual int Age29 { get; set; }
        public virtual int Age30 { get; set; }
        public virtual int Age31 { get; set; }
        public virtual int Age32 { get; set; }
        public virtual int Age33 { get; set; }
        public virtual int Age34 { get; set; }
        public virtual int Age35 { get; set; }
        public virtual int Age36 { get; set; }
        public virtual int Age37 { get; set; }
        public virtual int Age38 { get; set; }
        public virtual int Age39 { get; set; }
        public virtual int Age40 { get; set; }
        public virtual int Age41 { get; set; }
        public virtual int Age42 { get; set; }
        public virtual int Age43 { get; set; }
        public virtual int Age44 { get; set; }
        public virtual int Age45 { get; set; }
        public virtual int Age46 { get; set; }
        public virtual int Age47 { get; set; }
        public virtual int Age48 { get; set; }
        public virtual int Age49 { get; set; }
        public virtual int Age50 { get; set; }
        public virtual int Age51 { get; set; }
        public virtual int Age52 { get; set; }
        public virtual int Age53 { get; set; }
        public virtual int Age54 { get; set; }
        public virtual int Age55 { get; set; }
        public virtual int Age56 { get; set; }
        public virtual int Age57 { get; set; }
        public virtual int Age58 { get; set; }
        public virtual int Age59 { get; set; }
        public virtual int Age60 { get; set; }
        public virtual int Age61 { get; set; }
        public virtual int Age62 { get; set; }
        public virtual int Age63 { get; set; }
        public virtual int Age64 { get; set; }
        public virtual int Age65 { get; set; }
        public virtual int Age66 { get; set; }
        public virtual int Age67 { get; set; }
        public virtual int Age68 { get; set; }
        public virtual int Age69 { get; set; }
        public virtual int Age70 { get; set; }
        public virtual int Age71 { get; set; }
        public virtual int Age72 { get; set; }
        public virtual int Age73 { get; set; }
        public virtual int Age74 { get; set; }
        public virtual int Age75 { get; set; }
        public virtual int Age76 { get; set; }
        public virtual int Age77 { get; set; }
        public virtual int Age78 { get; set; }
        public virtual int Age79 { get; set; }
        public virtual int Age80 { get; set; }
        public virtual int Age81 { get; set; }
        public virtual int Age82 { get; set; }
        public virtual int Age83 { get; set; }
        public virtual int Age84 { get; set; }
        public virtual int Age85 { get; set; }
        public virtual int Age86 { get; set; }
        public virtual int Age87 { get; set; }
        public virtual int Age88 { get; set; }
        public virtual int Age89 { get; set; }
        public virtual int Age90 { get; set; }
        public virtual int Age91 { get; set; }
        public virtual int Age92 { get; set; }
        public virtual int Age93 { get; set; }
        public virtual int Age94 { get; set; }
        public virtual int Age95 { get; set; }
        public virtual int Age96 { get; set; }
        public virtual int Age97 { get; set; }
        public virtual int Age98 { get; set; }
        public virtual int Age99 { get; set; }
        public virtual int Age100 { get; set; }
        public virtual int Age101 { get; set; }
        public virtual int Age102 { get; set; }
        public virtual int Age103 { get; set; }
        public virtual int Age104 { get; set; }
        public virtual int Age105 { get; set; }
        public virtual int Age106 { get; set; }
        public virtual int Age107 { get; set; }
        public virtual int Age108 { get; set; }
        public virtual int Age109 { get; set; }
        public virtual int Age110 { get; set; }
        public virtual int Age111 { get; set; }
        public virtual int Age112 { get; set; }
        public virtual int Age113 { get; set; }
        public virtual int Age114 { get; set; }
        public virtual int Age115 { get; set; }
        public virtual int Age116 { get; set; }
        public virtual int Age117 { get; set; }
        public virtual int Age118 { get; set; }
        public virtual int Age119 { get; set; }
        public virtual int Age120 { get; set; }
        public virtual int Age121 { get; set; }
        public virtual int Age122 { get; set; }
        public virtual int Age123 { get; set; }
        public virtual int Age124 { get; set; }
        public virtual int Age125 { get; set; }
        public virtual int Age126 { get; set; }
        public virtual int Age127 { get; set; }
        public virtual int Age128 { get; set; }
        public virtual int Age129 { get; set; }
        public virtual int Age130 { get; set; }
        public virtual int Age131 { get; set; }
        public virtual int Age132 { get; set; }
        public virtual int Age133 { get; set; }
        public virtual int Age134 { get; set; }
        public virtual int Age135 { get; set; }
        public virtual int Age136 { get; set; }
        public virtual int Age137 { get; set; }
        public virtual int Age138 { get; set; }
        public virtual int Age139 { get; set; }
        public virtual int Age140 { get; set; }
        public virtual int Age141 { get; set; }
        public virtual int Age142 { get; set; }
        public virtual int Age143 { get; set; }
        public virtual int Age144 { get; set; }
        public virtual int Age145 { get; set; }
        public virtual int Age146 { get; set; }
        public virtual int Age147 { get; set; }
        public virtual int Age148 { get; set; }
        public virtual int Age149 { get; set; }
        public virtual int Age150 { get; set; }
        public virtual int Age151 { get; set; }
        public virtual int Age152 { get; set; }
        public virtual int Age153 { get; set; }
        public virtual int Age154 { get; set; }
        public virtual int Age155 { get; set; }
        public virtual int Age156 { get; set; }
        public virtual int Age157 { get; set; }
        public virtual int Age158 { get; set; }
        public virtual int Age159 { get; set; }
        public virtual int Age160 { get; set; }
        public virtual int Age161 { get; set; }
        public virtual int Age162 { get; set; }
        public virtual int Age163 { get; set; }
        public virtual int Age164 { get; set; }
        public virtual int Age165 { get; set; }
        public virtual int Age166 { get; set; }
        public virtual int Age167 { get; set; }
        public virtual int Age168 { get; set; }
        public virtual int Age169 { get; set; }
        public virtual int Age170 { get; set; }
        public virtual int Age171 { get; set; }
        public virtual int Age172 { get; set; }
        public virtual int Age173 { get; set; }
        public virtual int Age174 { get; set; }
        public virtual int Age175 { get; set; }
        public virtual int Age176 { get; set; }
        public virtual int Age177 { get; set; }
        public virtual int Age178 { get; set; }
        public virtual int Age179 { get; set; }
        public virtual int Age180 { get; set; }
        public virtual int Age181 { get; set; }
        public virtual int Age182 { get; set; }
        public virtual int Age183 { get; set; }
        public virtual int Age184 { get; set; }
        public virtual int Age185 { get; set; }
        public virtual int Age186 { get; set; }
        public virtual int Age187 { get; set; }
        public virtual int Age188 { get; set; }
        public virtual int Age189 { get; set; }
        public virtual int Age190 { get; set; }
        public virtual int Age191 { get; set; }
        public virtual int Age192 { get; set; }
        public virtual int Age193 { get; set; }
        public virtual int Age194 { get; set; }
        public virtual int Age195 { get; set; }
        public virtual int Age196 { get; set; }
        public virtual int Age197 { get; set; }
        public virtual int Age198 { get; set; }
        public virtual int Age199 { get; set; }
        public virtual int Age200 { get; set; }
        public virtual int Age201 { get; set; }
        public virtual int Age202 { get; set; }
        public virtual int Age203 { get; set; }
        public virtual int Age204 { get; set; }
        public virtual int Age205 { get; set; }
        public virtual int Age206 { get; set; }
        public virtual int Age207 { get; set; }
        public virtual int Age208 { get; set; }
        public virtual int Age209 { get; set; }
        public virtual int Age210 { get; set; }
        public virtual int Age211 { get; set; }
        public virtual int Age212 { get; set; }
        public virtual int Age213 { get; set; }
        public virtual int Age214 { get; set; }
        public virtual int Age215 { get; set; }
        public virtual int Age216 { get; set; }
        public virtual int Age217 { get; set; }
        public virtual int Age218 { get; set; }
        public virtual int Age219 { get; set; }
        public virtual int Age220 { get; set; }
        public virtual int Age221 { get; set; }
        public virtual int Age222 { get; set; }
        public virtual int Age223 { get; set; }
        public virtual int Age224 { get; set; }
        public virtual int Age225 { get; set; }
        public virtual int Age226 { get; set; }
        public virtual int Age227 { get; set; }
        public virtual int Age228 { get; set; }
        public virtual int Age229 { get; set; }
        public virtual int Age230 { get; set; }
        public virtual int Age231 { get; set; }
        public virtual int Age232 { get; set; }
        public virtual int Age233 { get; set; }
        public virtual int Age234 { get; set; }
        public virtual int Age235 { get; set; }
        public virtual int Age236 { get; set; }
        public virtual int Age237 { get; set; }
        public virtual int Age238 { get; set; }
        public virtual int Age239 { get; set; }
        public virtual int Age240 { get; set; }
        public virtual int Age241 { get; set; }
        public virtual int Age242 { get; set; }
        public virtual int Age243 { get; set; }
        public virtual int Age244 { get; set; }
        public virtual int Age245 { get; set; }
        public virtual int Age246 { get; set; }
        public virtual int Age247 { get; set; }
        public virtual int Age248 { get; set; }
        public virtual int Age249 { get; set; }
        public virtual int Age250 { get; set; }
    }
}
